namespace Hades.Syntax.Expression
{
    public enum Classifier
    {
        Root,
        With,
        VariableDeclaration,
        IntLiteral,
        BoolLiteral,
        StringLiteral,
        DecLiteral,
        Call,
        Identifier,
        Operation,
        NullCondition,
        Exception,
        Lambda,
        Put,
        Function,
        While,
        Command,
        ValueCall,
        Assignment,
        For,
        LeftHand,
        RightHand,
        Misc,
        ListLiteral,
        NullLiteral,
        MultiDimensionalArrayAccess
    }
}